
# path to dependencies
SAXON_JAR_PATH="/Users/laurentml/dev/tei/install/SaxonHE10-5J/saxon-he-10.5.jar"
TEI_XSL_STYLESHEETS_PATH="/Users/laurentml/dev/tei/install/tei-xsl"

# API URLs
rootUrl="https://dts.perseids.org/"
COLLECTIONS_URL=rootUrl+"collections"
DOCUMENTS_URL=rootUrl+"documents"
NAVIGATION_URL=rootUrl+"navigation"
DATASET_ID="perseids"

# where to start from
ROOT_COLLECTION_ID="urn:perseids:latinLit"

# where to store generated files
TARGET_PATH="/Users/laurentml/tmp/dts/perseids/"+"latin"

# set to None for no max depth
MAX_DEPTH=None

# set True to download TEI files
RETRIEVE_FILES=True
TRANSFORM_TEI_TO_TXT=True
TRANSFORM_TEI_TO_HTML=False

# inject plain text contents into (resources) CSV file
INLINE_TXT_IN_CSV=True

# -------------------------------------------

# OPTIONAL FUNCTION
# called every time we try to download a TEI file
# if this function returns False we will skip the file
# it it returns True we will actually download it.
#
# if this function is missing, it is assumed to be always True
def config_filterResource(resourceCsvData,resourceJsonData):
    return True # retrieve all TEI files
    #return resourceCsvData["language"]=="en" # retrieve on TEI files marked as english language

# OPTIONAL FUNCTION
# CSV ids might have some unicity or syntaxic constraints which
# can be handled here. Default behaviour is to remove 'urn' text and replace ':' by '.'
# to be compatible with Lucene query syntax (used by MetaindeX)
#def config_idDts2idCsv(dtsId,dtsJsonData):
#    return dtsId.replace('urn:','').replace(':','.').replace('urn.','')

# -------------------------------------------
def normalizeText(text):
    return text.replace("\n"," ").replace("  "," ").replace(";",".")

# at least 'url', 'urn', '@id', 'members' (and 'parent'), and '@type' are generated by default, others shall be listed hereunder
# <dts-id> : <csv-id>
ATTRS_LIST={
    "Collection" :{ "totalItems" : {"csvName":"nbChildren", "mandatory":True}, 
                    "title" : {"csvName":"title", "mandatory":True, "transform":normalizeText},
                    
                },
    
    
    "Resource":{ 
                "title" : {"csvName":"title", "mandatory":True, "transform":normalizeText},
                "description" : {"csvName":"description", "mandatory":True, "transform":normalizeText},
                "dts:dublincore/dc:language" : {"csvName":"language", "mandatory":True},
                
                
            }
 }