
import os
HOME=os.path.expanduser('~')

# path to dependencies
SAXON_JAR_PATH=HOME+"/dev/tei/install/SaxonHE10-5J/saxon-he-10.5.jar"
TEI_XSL_STYLESHEETS_PATH=HOME+"/dev/tei/install/tei-xsl"

# API URLs
rootUrl="https://dev.chartes.psl.eu/api/nautilus/dts/"
COLLECTIONS_URL=rootUrl+"collections"
DOCUMENTS_URL=rootUrl+"document"
NAVIGATION_URL=rootUrl+"navigation"
DATASET_ID="thesesENC"

# where to start from
ROOT_COLLECTION_ID="urn:cts:frenchLit:pos2012"#"default"

# where to store generated files
TARGET_PATH=HOME+"/tmp/dts/thesesENC/2012"

# set to None for no max depth
MAX_DEPTH=None

# set True to download TEI files
RETRIEVE_FILES=True
TRANSFORM_TEI_TO_TXT=True
TRANSFORM_TEI_TO_HTML=True

# inject plain text contents into (resources) CSV file
INLINE_TXT_IN_CSV=True

# -------------------------------------------

# OPTIONAL FUNCTION
# called every time we try to download a TEI file
# if this function returns False we will skip the file
# it it returns True we will actually download it.
#
# if this function is missing, it is assumed to be always True
#def config_filterResource(resourceCsvData,resourceJsonData):
#    return resourceCsvData["language"]=="fr"

# OPTIONAL FUNCTION
# CSV ids might have some unicity or syntaxic constraints which
# can be handled here. Default behaviour is to remove 'urn' text and replace ':' by '.'
# to be compatible with Lucene query syntax (used by MetaindeX)
#def config_idDts2idCsv(dtsId,dtsJsonData):
#    return dtsId.replace('urn:','').replace(':','.').replace('urn.','')

# -------------------------------------------

def replaceCr(text):
    return text.replace("\n"," ").replace("  "," ")


# at least 'url', 'urn', '@id', 'members' (and 'parent'), and '@type' are generated by default, others shall be listed hereunder
# <dts-id> : <csv-id>
ATTRS_LIST={
    "Collection" :{ "totalItems" : {"csvName":"nbChildren", "mandatory":True}, 
                    "title" : {"csvName":"title", "mandatory":True, "transform":replaceCr},
                    "dts:extensions/ns2:creator[0]/@value" : {"csvName":"author", "mandatory":False},
                    "dts:extensions/ns2:date" : {"csvName":"date", "mandatory":False},
                },
    
    
    "Resource":{ 
                "dts:extensions/ns2:language" : {"csvName":"language", "mandatory":True},
                
                
            }
 }

