

version: '3'

networks:
 mxnet:
services:
 mx-conf-db:
   #build: ./mysql
   image: mysql:5
   container_name: mxsql
   #command: --default-authentication-plugin=mysql_native_password
   networks:
     - mxnet
   environment:
    - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE=metaindex
    - MYSQL_LOG_CONSOLE=true
    #- MYSQL_RANDOM_ROOT_PASSWORD=true
    - MYSQL_USER=$MYSQL_USER
    - MYSQL_PASSWORD=$MYSQL_PASSWORD
   volumes:
        - mx-conf-data:/var/lib/mysql
        - ./mysql/1-dbreset.sql:/docker-entrypoint-initdb.d/1-dbreset.sql
        - ./mysql/2-create-dbentries-prod.sql:/docker-entrypoint-initdb.d/2-create-dbentries-prod.sql
        - ./mysql/3-create-dbentries-dev.sql:/docker-entrypoint-initdb.d/3-create-dbentries-dev.sql
        - ./mysql/my.cnf:/etc/mysql/my.cnf   
   expose:
      - $MYSQLPORT
   # for dev only, so that Metaindex from Eclipse debugger can access MySQL DB
   ports:
      - $MYSQLPORT:$MYSQLPORT

 mx-conf-dbexplorer:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     environment:   
     # Values hardcoded in metaindex/WEB-INF/applicationContext.xml   
      - PMA_HOST=mxsql 
      - PMA_PORT=$MYSQLPORT
     networks:
      - mxnet
     restart: always
     ports:
      - $PHPMYADMIN_PUBLIC_PORT:80  
     links:
      - mx-conf-db   
     depends_on:
      - mx-conf-db

 mx-docs-db:
     image: elasticsearch:$ELK_VERSION
     container_name: elasticsearch
     environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     ulimits:
       memlock:
        soft: -1
        hard: -1
     networks:
      - mxnet
     expose:
      - $ELASTICSEARCH_PORT1
      - $ELASTICSEARCH_PORT2
    # for dev only, so that Metaindex from Eclipse can access ElasticSearch DB
     ports:
       - $ELASTICSEARCH_PORT1:$ELASTICSEARCH_PORT1
       - $ELASTICSEARCH_PORT2:$ELASTICSEARCH_PORT2
     volumes:
       - mx-docs-data:/usr/share/elasticsearch/data
       #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

 mx-stats-gui:
    image: kibana:$ELK_VERSION
    container_name: kibana    
    links:
      - mx-docs-db
    ports:
      - $KIBANA_PUBLIC_PORT:5601
    depends_on:
      - mx-docs-db
    networks:
      - mxnet    

volumes:
  mx-conf-data:
  mx-docs-data:
