

TARGET_PATH="/Users/laurentml/tmp/dts/alpheios"
RETRIEVE_FILES=True

rootUrl="https://texts.alpheios.net/api/dts/"
COLLECTIONS_URL=rootUrl+"collections"
DOCUMENTS_URL=rootUrl+"document"
NAVIGATION_URL=rootUrl+"navigation"

DATASET_ID="some_id"
DATASET_NAME="Alpheios"

ROOT_COLLECTION_ID=""

# set to None for no max depth
MAX_DEPTH=None

def config_idDts2idCsv(idDts):
    return idDts.replace('urn:alpheios:','').replace(':','.').replace('urn.','')


def replaceCr(text):
    return text.replace("\n"," ").replace("  "," ")

# at least 'url', 'urn', '@id', 'members' (and 'parent'), and '@type' are generated by default, others shall be listed hereunder
# <dts-id> : <csv-id>
ATTRS_LIST={
    "Collection" :{ "totalItems" : {"csvName":"nbChildren", "mandatory":True}, 
                    "title" : {"csvName":"title", "mandatory":True, "transform":replaceCr}
                },
    
    
    "Resource":{ 
                "dts:extensions/ns1:language" : {"csvName":"language", "mandatory":True},
                "dts:extensions/cts:description[0]/@value" : {"csvName":"description", "mandatory":True,"transform":replaceCr},
            }
 }